/* Currículo MEDCURSO 2026, extraído do MEDPlanner (Notion).
   [semana, área, título, aula, questões, desempenho, data, degraus, [bônus]] */
export const SEED = [
  [1,"GO","Ciclo Menstrual e Anticoncepção",1,1,2,"2026-05-24",3,["Síndrome Pré-Menstrual (SPM) e Síndrome Disfórica Pré-Menstrual (SDPM)","Incongruência de Gênero"]],
  [1,"CL","Glomerulopatias I (Nefrítica, Alterações Assintomáticas, GNRP)",1,1,1,"2026-08-14",0,["Alport"]],
  [2,"GO","Amenorreia e Ovário Policístico",1,1,1,"2026-08-14",0,[]],
  [2,"CL","Glomerulopatias II (Síndrome Nefrótica, Glomerulopatias nas Desordens Sistêmicas)",1,1,1,"2026-08-25",1,[]],
  [3,"CI","Trauma I: Avaliação Inicial e Trauma de Tórax",1,1,2,"2026-09-27",3,["Trauma Cervical","Trauma de Abdome - Lesões Específicas","Lesão de Extremidade","Atualização ATLS - 11ª Edição"]],
  [3,"CI","Trauma II: Trauma de Abdome, Pelve e TCE",1,1,2,"2026-09-27",3,[]],
  [4,"GO","Diagnóstico de Gravidez, Modificações do Organismo Materno e Pré-Natal",1,1,2,"2026-04-18",2,["Aconselhamento Genético Pré-Natal"]],
  [4,"CL","Distúrbio Hidroeletrolítico",1,1,2,"2026-04-18",2,["Nefrotoxicidade por Contraste","Rabdomiólise","Acidose Tubular Renal","Aspectos Práticos no Tratamento da Hiponatremia","Hipernatremia"]],
  [5,"CL","Insuficiência Renal",1,1,1,"2026-04-04",1,["Terapia de Substituição Renal - HD e DP","Terapia de Substituição Renal - Transplante"]],
  [5,"CL","Distúrbio Ácido-Básico",1,1,1,"2026-04-01",1,["Relação Delta-Delta"]],
  [6,"PR","Medidas de Saúde Coletiva",1,1,1,"2026-04-03",1,["Sistemas de Informação","Outros Indicadores e Censo 2022"]],
  [6,"PE","Neonatologia I",1,1,1,"2026-05-02",1,["*Triagem Neonatal","O Exame Físico Neonatal"]],
  [8,"PR","Estudos Epidemiológicos",1,1,2,"2026-04-01",0,["Variáveis","Testes Estatísticos","Fases do Ensaio Clínico","Estudos Descritivos e Metanálise"]],
  [8,"CI","Urologia",1,1,2,"2026-04-01",0,["Câncer de Bexiga","Câncer de Rim","Disfunção Erétil","Câncer do Testículo","Hipogonadismo Masculino e Testosterona"]],
  [9,"CL","Introdução à Reumatologia + Artrites (Artrite Reumatoide, Espondiloartropatias Soronegativas)",1,1,2,"2026-04-01",0,["AINEs e Glicocorticoides"]],
  [9,"PE","Neonatologia II",1,1,2,"2026-05-02",1,["Enterocolite Necrosante","Miscelânea"]],
  [10,"CL","Gota; Febre Reumática",1,1,1,"2026-03-30",0,["Artrite Séptica","Policondrite Recidivante","Febre Familiar do Mediterrâneo","Fibromialgia","Artropatia por Pirofosfato de Cálcio"]],
  [10,"PR","Epidemiologia Clínica",1,1,2,"2026-04-01",0,["Verossimilhança e Testes Múltiplos","Curva ROC e Variações no Ponto de Corte","Medidas de Tendência Central e de Dispersão"]],
  [11,"GO","Assistência Clínica ao Parto e Parto Prematuro",1,1,2,"2026-04-18",0,["Estudo do Motor","Mecanismo de Parto","Cesariana"]],
  [11,"CI","Queimadura e Cirurgia Plástica",1,1,2,"2026-04-18",0,["*REMIT","Suporte Nutricional"]],
  [12,"CL","Colagenoses",1,1,0,"2026-04-18",0,["Miopatias Inflamatórias Idiopáticas","Doença Mista do Tecido Conjuntivo","Síndrome de Sjögren","Amiloidoses"]],
  [12,"PR","Vigilância da Saúde",1,1,1,"2026-04-18",0,["Glossário de Doenças Infecciosas","Processo Epidêmico"]],
  [13,"CI","Cirurgia Pediátrica",1,1,1,"2026-05-24",0,[]],
  [13,"PR","Saúde do Trabalhador + Ética Médica",1,0,0,"2026-05-11",0,["Saúde do Trabalhador: Saturnismo, Hidrargirismo, Benzenismo e Cromo"]],
  [14,"PE","Aleitamento Materno",1,1,1,"2026-05-24",0,["Alimentação Complementar"]],
  [15,"PE","Crescimento e Desenvolvimento Normais; Puberdade Normal",0,0,0,null,0,["Distúrbios Puberais"]],
  [15,"CL","Anemias I - Introdução, Ferropriva, Doença Crônica, Megaloblástica",0,0,0,null,0,["Mielodisplasia","Anemia Sideroblástica","Anemia Aplásica"]],
  [16,"CL","Leucemias Agudas e Crônicas",0,0,0,null,0,[]],
  [16,"CL","Anemia II - Introdução às Anemias Hemolíticas / Anemia Falciforme e Outras Hemoglobinopatias",0,0,0,null,0,["Hemoglobinúria Paroxística Noturna","Porfiria","Talassemias"]],
  [17,"CL","Linfomas e Mieloma Múltiplo",0,0,0,null,0,[]],
  [17,"CI","Preparo Pré-Operatório, Risco Cirúrgico e Complicações em Cirurgia",0,0,0,null,0,["*Anestesiologia","Fios de Sutura","Profilaxia de TEP e TVP"]],
  [18,"CL","Distúrbios da Hemostasia",0,0,0,null,0,["Hemotransfusão","Hemofilias","Trombofilias"]],
  [18,"CI","Hérnias da Parede Abdominal",1,0,0,"2026-05-19",0,["*Abordagem Laparoscópica","Outras Hérnias","Hérnias na Infância"]],
  [19,"CL","Doenças do Esôfago",1,1,1,"2026-05-28",0,["Perfuração Esofágica (Boerhaave)","Esofagites"]],
  [19,"GO","Sangramento Uterino Anormal, Endometriose e Infertilidade",1,1,2,"2026-07-16",0,["*Infertilidade","Dismenorreia e os Pólipos Endometriais"]],
  [20,"CL","Doenças do Estômago",1,1,1,"2026-07-16",0,["*Hemorragia Digestiva Alta","GIST","Linfoma Gástrico","Síndrome de Zollinger-Ellison"]],
  [20,"CL","Doenças Clínicas do Intestino",1,1,2,"2026-08-06",0,["Colite Pseudomembranosa","Síndrome do Intestino Irritável"]],
  [21,"CL","Doenças Cirúrgicas do Intestino I - Vascular e Obstrução",1,1,1,"2026-08-08",0,["Ingestão de Corpo Estranho"]],
  [21,"GO","Sangramentos na Gravidez - Parte I",0,0,0,null,0,[]],
  [22,"CL","Doenças Cirúrgicas do Intestino II - Diverticulose, Polipose, Câncer e Apendicite Aguda",0,0,0,null,0,["*Hemorragia Digestiva Baixa","Tumores Carcinoides","Tumores do Apêndice","Câncer de Canal Anal"]],
  [22,"GO","Sangramentos na Gravidez - Parte II e Doença Hemolítica Perinatal",0,0,0,null,0,[]],
  [23,"CL","Doença das Vias Biliares",0,0,0,null,0,["Neoplasias das Vias Biliares","Lesão Iatrogênica da Via Biliar","Cistos de Via Biliar","Colangite Esclerosante Primária"]],
  [23,"CL","Pancreatite Aguda e Crônica; Câncer de Pâncreas",0,0,0,null,0,["Tumores Neuroendócrinos do Pâncreas","Neoplasias Císticas do Pâncreas"]],
  [24,"CL","Introdução à Hepatologia; Hepatites Virais",0,0,0,null,0,["Insuficiência Hepática Aguda"]],
  [24,"CL","Cirrose e suas Causas",0,0,0,null,0,["Hepatite Medicamentosa"]],
  [25,"CL","Cirrose e suas Complicações / Hipertensão Porta; Ascite; Encefalopatia",0,0,0,null,0,["Abscesso Hepático Bacteriano","Tumores Hepáticos Benignos","Tumores Hepáticos Malignos"]],
  [25,"GO","Climatério, Distopia e Incontinência Urinária",0,0,0,null,0,["*Osteoporose","Fístulas Genitais e Síndrome da Bexiga Dolorosa","Anatomia em GO - Pelve Óssea, Assoalho e Períneo","Anatomia em GO - Estruturas Pélvicas"]],
  [26,"PE","Distúrbios do Crescimento: Desnutrição e Baixa Estatura",0,0,0,null,0,["Carência de Micronutrientes","Síndromes Genéticas"]],
  [26,"CL","Arritmias I (Taquiarritmias)",0,0,0,null,0,["Bloqueios de Ramo"]],
  [27,"PE","Imunização",0,0,0,null,0,["Profilaxia para raiva","Profilaxia para o tétano acidental"]],
  [27,"CL","Arritmias II (Bradiarritmias) + PCR",0,0,0,null,0,["Marca-passo: conceitos básicos","Marca-passo: funcionamento do marca-passo definitivo","Síncope"]],
  [28,"CL","Insuficiência Cardíaca",0,0,0,null,0,["Choque em pediatria","Hipertensão pulmonar","Cardiomiopatia dilatada","Cardiomiopatia hipertrófica","Cardiomiopatia restritiva","Cardiomiopatia de estresse (takotsubo)","Aula especial - insuficiência cardíaca aguda","Choque: monitorização hemodinâmica e perfusional","Choque: tratamento"]],
  [28,"GO","Doença das Mamas e Ovários",0,0,0,null,0,[]],
  [29,"CL","Hipertensão Arterial Sistêmica; Crise Hipertensiva",0,0,0,null,0,[]],
  [29,"CL","Valvopatias",0,0,0,null,0,[]],
  [30,"PE","Diarreia Aguda e Desidratação na Infância",0,0,0,null,0,["Constipação na Infância","Diarreia Crônica"]],
  [30,"CL","Doença Arterial Coronariana: IAM e Angina",0,0,0,null,0,["Complicações Pós-IAM","Pericardiopatias"]],
  [31,"PR","SUS I - Evolução Histórica e Legislação",0,0,0,null,0,["Decreto 7.508"]],
  [31,"GO","Lesões Precursoras, Câncer de Colo Uterino e Endométrio",0,0,0,null,0,["Câncer de Vulva"]],
  [32,"CL","Tireoide",0,0,0,null,0,["Hipotireoidismo Congênito"]],
  [32,"PR","SUS II - Atenção Básica e Financiamento",0,0,0,null,0,["Instrumentos de AB (Tipos de Família)","Instrumentos de AB (Ciclo de Vida Familiar)","Instrumentos de AB (Apgar Familiar, Practice e Firo)","Instrumentos de AB (Escala de Coelho Savassi)","Método SOAP","Cofinanciamento Federal da APS"]],
  [33,"PE","Infecções Respiratórias Agudas - Parte I",0,0,0,null,0,["Rinite Alérgica","Estridor Crônico e Aspiração de Corpo Estranho","Epistaxe"]],
  [33,"CL","Doenças da Suprarrenal",0,0,0,null,0,["Hipotálamo e Hipófise","Hiperaldosteronismo Primário"]],
  [34,"CL","Diabetes Mellitus",0,0,0,null,0,["Hipoglicemia","Doença Renal do Diabetes e Retinopatia Diabética","Neuropatia Diabética e Pé Diabético","*Dislipidemia"]],
  [34,"PE","Infecções Respiratórias Agudas - Parte II",0,0,0,null,0,["Fibrose Cística"]],
  [35,"CL","Asma e DPOC",0,0,0,null,0,["Ventilação Mecânica","Capnografia","USG de Tórax","Insuficiência Respiratória","Síndrome do Desconforto Respiratório Agudo","Provas de Função Pulmonar"]],
  [35,"GO","Distúrbios Hipertensivos da Gestação, Diabetes e Gemelaridade",0,0,0,null,0,["Doenças Intercorrentes na Gestação"]],
  [36,"CL","Câncer de Pulmão, TEP",0,0,0,null,0,["*Nódulo Pulmonar Solitário","Embolia Gordurosa","Tumores do Mediastino","Pneumopatias Intersticiais Difusas","Sarcoidose","Hemoptise"]],
  [36,"PE","Nefrologia Pediátrica",0,0,0,null,0,["*Parada Cardiorrespiratória na Infância","*Cardiopatias Congênitas","HAS na infância"]],
  [37,"CL","Pneumonia e Complicações",0,0,0,null,0,["As aulas bônus são as mesmas de Tuberculose"]],
  [37,"CL","Tuberculose",0,0,0,null,0,["Influenza","Aspergilose","Histoplasmose","*Paracoccidioidomicose","*Derrame pleural"]],
  [38,"CL","AIDS",0,0,0,null,0,["Gastroids","*HIV na infância","HTLV","Citomegalovírus"]],
  [38,"CL","Parasitoses Intestinais",0,0,0,null,0,["Esquistossomose","Toxoplasmose","Acidente por Animais Peçonhentos"]],
  [39,"GO","Sofrimento Fetal, Avaliação da Vitalidade Fetal, Fórcipe e Puerpério",0,0,0,null,0,["Distúrbios do Humor e Tromboembolismo"]],
  [39,"CL","Endocardite Infecciosa / Meningite",0,0,0,null,0,["Infecção Relacionada a Cateter","Meningoencefalite Herpética","Abscesso Cerebral","*ITU","*Sepse e Choque Séptico"]],
  [40,"CL","Síndromes Febris",0,0,0,null,0,["Febre Tifoide","Malária","Febre Maculosa Brasileira","Covid-19","Febre do Oropouche","Doença de Chagas","*Leishmaniose Visceral"]],
  [40,"GO","IST",0,0,0,null,0,["Síndrome das verrugas genitais"]],
  [41,"CL","Neurologia I (Cefaleias, Epilepsias)",0,0,0,null,0,["Tumores do SNC","Vertigem","Hipertensão Intracraniana","Coma","Trombose Venosa Cerebral","Ataque isquêmico transitório","Morte encefálica"]],
  [41,"CL","Neurologia II (Síndromes Neurológicas e AVE)",0,0,0,null,0,["As aulas bônus são as mesmas de Neurologia I"]],
  [42,"PE","Doenças Exantemáticas na Infância",0,0,0,null,0,["Febre Sem Sinais de Localização","Erros Inatos da Imunidade","Tumores Abdominais na Infância","Prevenção de Acidentes e Maus-Tratos na Infância"]],
  [42,"CL","Neurologia III (Polineuropatias, Demência, Parkinson)",0,0,0,null,0,["Cuidados paliativos","Distrofias musculares","Hipertermia maligna","Hérnia de disco","Doenças da placa motora"]],
  [43,"CL","Psiquiatria I",0,0,0,null,0,["Intoxicações Exógenas","Suicídio","Transtorno de personalidade","Transtornos do Neurodesenvolvimento"]],
  [43,"CL","Psiquiatria II",0,0,0,null,0,["As aulas bônus são as mesmas de Psiquiatria I"]],
  [43,"CI","Oftalmologia",0,0,0,null,0,[]],
  [44,"CI","Especialidade Cirúrgica - Parte I",0,0,0,null,0,["*Cirurgia de Cabeça e Pescoço","Cisto Pilonidal","Câncer de Canal Anal"]],
  [44,"CI","Especialidade Cirúrgica - Parte II",0,0,0,null,0,["As aulas bônus são as mesmas da Parte I"]],
  [45,"CL","Dermatologia I",0,0,0,null,0,["Anafilaxia","*Piodermites","Acne vulgar","Mpox","Herpes-Zóster","Angioedema Hereditário"]],
  [45,"CL","Dermatologia II",0,0,0,null,0,["As aulas bônus são as mesmas de Dermatologia I"]],
  [46,"CI","Ortopedia I",0,0,0,null,0,["Ortopedia - Doenças periarticulares"]],
  [46,"CI","Ortopedia II",0,0,0,null,0,["As aulas bônus são as mesmas de Ortopedia I"]],
];
